import type { Lecture, Project, Module } from '@/lib/types';

export const SEED_LECTURES: Omit<Lecture, 'status' | 'completionDate' | 'notes' | 'revisionNeeded' | 'tags'>[] = [
  // ─── Introduction ────────────────────────────────────────────────────
  { id: 'lec-001', name: "What You'll Get in This Course", module: 'Introduction', duration: 188, isProject: false },
  { id: 'lec-002', name: 'Download the Course Syllabus', module: 'Introduction', duration: 12, isProject: false },
  { id: 'lec-003', name: 'Download the 12 Rules to Learn to Code eBook [Latest Edition]', module: 'Introduction', duration: 42, isProject: false },
  { id: 'lec-004', name: 'Download the Required Software', module: 'Introduction', duration: 43, isProject: false },
  { id: 'lec-005', name: 'How Does the Internet Actually Work?', module: 'Introduction', duration: 327, isProject: false },
  { id: 'lec-006', name: 'How Do Websites Actually Work?', module: 'Introduction', duration: 502, isProject: false },
  { id: 'lec-007', name: 'How to Get the Most Out of the Course', module: 'Introduction', duration: 573, isProject: false },
  { id: 'lec-008', name: "How to Get Help When You're Stuck", module: 'Introduction', duration: 399, isProject: false },
  { id: 'lec-009', name: 'Pathfinder', module: 'Introduction', duration: 143, isProject: false },
  { id: 'lec-010', name: 'A Note About 2023 Course Updates', module: 'Introduction', duration: 36, isProject: false },

  // ─── HTML ────────────────────────────────────────────────────────────
  { id: 'lec-011', name: 'What is HTML?', module: 'HTML', duration: 258, isProject: false },
  { id: 'lec-012', name: 'How to Download the Course Resources', module: 'HTML', duration: 163, isProject: false },
  { id: 'lec-013', name: 'HTML Heading Elements', module: 'HTML', duration: 864, isProject: false },
  { id: 'lec-014', name: 'HTML Paragraph Elements', module: 'HTML', duration: 520, isProject: false },
  { id: 'lec-015', name: 'Self Closing Tags', module: 'HTML', duration: 700, isProject: false },
  { id: 'lec-016', name: '[Project] Movie Ranking', module: 'HTML', duration: 343, isProject: true },
  { id: 'lec-017', name: 'How to Ace this Course', module: 'HTML', duration: 84, isProject: false },
  { id: 'lec-018', name: 'The List Element', module: 'HTML', duration: 632, isProject: false },
  { id: 'lec-019', name: 'Nesting and Indentation', module: 'HTML', duration: 849, isProject: false },
  { id: 'lec-020', name: 'Anchor Elements', module: 'HTML', duration: 645, isProject: false },
  { id: 'lec-021', name: 'Image Elements', module: 'HTML', duration: 497, isProject: false },
  { id: 'lec-022', name: '[Project] Birthday Invite', module: 'HTML', duration: 241, isProject: true },
  { id: 'lec-023', name: 'Tip from Angela - Habit Building with the Calendar Trick', module: 'HTML', duration: 172, isProject: false },
  { id: 'lec-024', name: 'Get Access to the Monthly App Brewery Newsletter', module: 'HTML', duration: 56, isProject: false },
  { id: 'lec-025', name: 'Computer File Paths', module: 'HTML', duration: 1160, isProject: false },
  { id: 'lec-026', name: 'What are Webpages?', module: 'HTML', duration: 775, isProject: false },
  { id: 'lec-027', name: 'The HTML Boilerplate', module: 'HTML', duration: 773, isProject: false },
  { id: 'lec-028', name: '[Project] Portfolio Website', module: 'HTML', duration: 514, isProject: true },
  { id: 'lec-029', name: 'How to Host Your Website for Free with GitHub', module: 'HTML', duration: 513, isProject: false },
  { id: 'lec-030', name: 'Introduction to Capstone Projects', module: 'HTML', duration: 306, isProject: false },
  { id: 'lec-031', name: 'Instructions for Capstone Project 1 - Online Resume', module: 'HTML', duration: 142, isProject: false },

  // ─── CSS ─────────────────────────────────────────────────────────────
  { id: 'lec-032', name: 'Why do we need CSS?', module: 'CSS', duration: 524, isProject: false },
  { id: 'lec-033', name: 'How to add CSS', module: 'CSS', duration: 919, isProject: false },
  { id: 'lec-034', name: 'CSS Quiz', module: 'CSS', duration: 30, isProject: false },
  { id: 'lec-035', name: 'CSS Selectors', module: 'CSS', duration: 1376, isProject: false },
  { id: 'lec-036', name: '[Project] Colour Vocab Website', module: 'CSS', duration: 548, isProject: true },
  { id: 'lec-037', name: 'Tip from Angela - Dealing with Distractions', module: 'CSS', duration: 148, isProject: false },
  { id: 'lec-038', name: 'Join the Student Community', module: 'CSS', duration: 39, isProject: false },
  { id: 'lec-039', name: 'CSS Colours', module: 'CSS', duration: 425, isProject: false },
  { id: 'lec-040', name: 'Font Properties', module: 'CSS', duration: 1286, isProject: false },
  { id: 'lec-041', name: 'Inspecting CSS', module: 'CSS', duration: 712, isProject: false },
  { id: 'lec-042', name: 'The CSS Box Model - Margin, Padding and Border', module: 'CSS', duration: 1245, isProject: false },
  { id: 'lec-043', name: '[Project] Motivational Poster Website', module: 'CSS', duration: 457, isProject: true },
  { id: 'lec-044', name: 'The Cascade - Specificity and Inheritance', module: 'CSS', duration: 1528, isProject: false },
  { id: 'lec-045', name: 'Combining CSS Selectors', module: 'CSS', duration: 1392, isProject: false },
  { id: 'lec-046', name: 'CSS Positioning', module: 'CSS', duration: 1370, isProject: false },
  { id: 'lec-047', name: '[Project] CSS Flag', module: 'CSS', duration: 1075, isProject: true },
  { id: 'lec-048', name: 'Tip from Angela - Nothing Easy is Worth Doing!', module: 'CSS', duration: 215, isProject: false },
  { id: 'lec-049', name: 'CSS Display', module: 'CSS', duration: 690, isProject: false },
  { id: 'lec-050', name: 'CSS Float', module: 'CSS', duration: 699, isProject: false },
  { id: 'lec-051', name: 'How to Create Responsive Websites', module: 'CSS', duration: 1124, isProject: false },
  { id: 'lec-052', name: 'Media Queries', module: 'CSS', duration: 632, isProject: false },
  { id: 'lec-053', name: '[Project] Web Design Agency Website', module: 'CSS', duration: 426, isProject: true },
  { id: 'lec-054', name: 'Tip from Angela - How to Deal with Procrastination', module: 'CSS', duration: 248, isProject: false },

  // ─── Flexbox ─────────────────────────────────────────────────────────
  { id: 'lec-055', name: 'Display: Flex', module: 'Flexbox', duration: 861, isProject: false },
  { id: 'lec-056', name: 'Flex Direction', module: 'Flexbox', duration: 823, isProject: false },
  { id: 'lec-057', name: 'Flex Layout', module: 'Flexbox', duration: 1162, isProject: false },
  { id: 'lec-058', name: 'Flex Sizing', module: 'Flexbox', duration: 1467, isProject: false },
  { id: 'lec-059', name: '[Project] Pricing Table', module: 'Flexbox', duration: 608, isProject: true },
  { id: 'lec-060', name: 'Tip from Angela - Building a Programming Habit', module: 'Flexbox', duration: 167, isProject: false },

  // ─── Grid ────────────────────────────────────────────────────────────
  { id: 'lec-061', name: 'Display: Grid', module: 'Grid', duration: 895, isProject: false },
  { id: 'lec-062', name: 'Grid Sizing', module: 'Grid', duration: 1412, isProject: false },
  { id: 'lec-063', name: 'Grid Placement', module: 'Grid', duration: 1577, isProject: false },
  { id: 'lec-064', name: '[Project] Mondrian Painting', module: 'Grid', duration: 405, isProject: true },

  // ─── Bootstrap ───────────────────────────────────────────────────────
  { id: 'lec-065', name: 'What is Bootstrap?', module: 'Bootstrap', duration: 935, isProject: false },
  { id: 'lec-066', name: 'Bootstrap Layout', module: 'Bootstrap', duration: 1273, isProject: false },
  { id: 'lec-067', name: 'Bootstrap Components', module: 'Bootstrap', duration: 1899, isProject: false },
  { id: 'lec-068', name: '[Project] TinDog Startup Website', module: 'Bootstrap', duration: 1882, isProject: true },

  // ─── Web Design ──────────────────────────────────────────────────────
  { id: 'lec-069', name: 'Introduction to Web Design', module: 'Web Design', duration: 235, isProject: false },
  { id: 'lec-070', name: 'Understanding Colour Theory', module: 'Web Design', duration: 544, isProject: false },
  { id: 'lec-071', name: 'Understanding Typography and How to Choose a Font', module: 'Web Design', duration: 628, isProject: false },
  { id: 'lec-072', name: 'Manage ATTENTION with effective User Interface (UI) Design', module: 'Web Design', duration: 627, isProject: false },
  { id: 'lec-073', name: 'User Experience (UX) Design', module: 'Web Design', duration: 819, isProject: false },
  { id: 'lec-074', name: "Web Design in Practice - Let's apply what we've learnt!", module: 'Web Design', duration: 1100, isProject: false },
  { id: 'lec-075', name: 'Instructions', module: 'Web Design', duration: 128, isProject: false },

  // ─── JavaScript ──────────────────────────────────────────────────────
  { id: 'lec-076', name: 'Introduction to Javascript', module: 'JavaScript', duration: 709, isProject: false },
  { id: 'lec-077', name: 'Javascript Alerts - Adding Behaviour to Websites', module: 'JavaScript', duration: 861, isProject: false },
  { id: 'lec-078', name: 'Data Types', module: 'JavaScript', duration: 246, isProject: false },
  { id: 'lec-079', name: 'Javascript Variables', module: 'JavaScript', duration: 575, isProject: false },
  { id: 'lec-080', name: 'Javascript Variables Exercise Start', module: 'JavaScript', duration: 168, isProject: false },
  { id: 'lec-081', name: 'Javascript Variables Exercise', module: 'JavaScript', duration: 30, isProject: false },
  { id: 'lec-082', name: 'Javascript Variables Exercise Solution', module: 'JavaScript', duration: 208, isProject: false },
  { id: 'lec-083', name: 'Naming and Naming Conventions for Javascript Variables', module: 'JavaScript', duration: 429, isProject: false },
  { id: 'lec-084', name: 'Javascript Variable Naming Quiz', module: 'JavaScript', duration: 30, isProject: false },
  { id: 'lec-085', name: 'String Concatenation', module: 'JavaScript', duration: 187, isProject: false },
  { id: 'lec-086', name: 'String Lengths and Retrieving the Number of Characters', module: 'JavaScript', duration: 384, isProject: false },
  { id: 'lec-087', name: 'Slicing and Extracting Parts of a String', module: 'JavaScript', duration: 536, isProject: false },
  { id: 'lec-088', name: 'Challenge: Changing Casing in Text', module: 'JavaScript', duration: 219, isProject: false },
  { id: 'lec-089', name: 'Challenge: Changing String Casing Solution', module: 'JavaScript', duration: 539, isProject: false },
  { id: 'lec-090', name: 'Basic Arithmetic and the Modulo Operator in Javascript', module: 'JavaScript', duration: 374, isProject: false },
  { id: 'lec-091', name: 'Increment and Decrement Expressions', module: 'JavaScript', duration: 148, isProject: false },
  { id: 'lec-092', name: 'Javascript Numbers Quiz', module: 'JavaScript', duration: 30, isProject: false },
  { id: 'lec-093', name: 'Functions Part 1: Creating and Calling Functions', module: 'JavaScript', duration: 635, isProject: false },
  { id: 'lec-094', name: 'Functions Part 1 Challenge - The Karel Robot', module: 'JavaScript', duration: 548, isProject: false },
  { id: 'lec-095', name: 'The Karel Chess Board Solution', module: 'JavaScript', duration: 18, isProject: false },
  { id: 'lec-096', name: 'A Quick Note About the Next Lesson', module: 'JavaScript', duration: 12, isProject: false },
  { id: 'lec-097', name: 'Functions Part 2: Parameters and Arguments', module: 'JavaScript', duration: 592, isProject: false },
  { id: 'lec-098', name: 'Life in Weeks Coding Exercise', module: 'JavaScript', duration: 30, isProject: false },
  { id: 'lec-099', name: 'Life in Weeks Solution', module: 'JavaScript', duration: 224, isProject: false },
  { id: 'lec-100', name: 'Functions Part 3: Outputs & Return Values', module: 'JavaScript', duration: 676, isProject: false },
  { id: 'lec-101', name: 'Challenge: Create a BMI Calculator', module: 'JavaScript', duration: 109, isProject: false },
  { id: 'lec-102', name: 'BMI Calculator Challenge', module: 'JavaScript', duration: 30, isProject: false },
  { id: 'lec-103', name: 'Challenge: BMI Calculator Solution', module: 'JavaScript', duration: 339, isProject: false },
  { id: 'lec-104', name: 'JavaScript Functions Quiz', module: 'JavaScript', duration: 30, isProject: false },
  { id: 'lec-105', name: 'Tip from Angela - Set Your Expectations', module: 'JavaScript', duration: 155, isProject: false },
  { id: 'lec-106', name: 'Random Number Generation in Javascript: Building a Love Calculator', module: 'JavaScript', duration: 675, isProject: false },
  { id: 'lec-107', name: 'Control Statements: Using If-Else Conditionals & Logic', module: 'JavaScript', duration: 288, isProject: false },
  { id: 'lec-108', name: 'Comparators and Equality', module: 'JavaScript', duration: 171, isProject: false },
  { id: 'lec-109', name: 'Combining Comparators', module: 'JavaScript', duration: 166, isProject: false },
  { id: 'lec-110', name: 'BMI Calculator Advanced (IF/ELSE)', module: 'JavaScript', duration: 30, isProject: false },
  { id: 'lec-111', name: 'Introducing the Leap Year Code Challenge', module: 'JavaScript', duration: 256, isProject: false },
  { id: 'lec-112', name: 'Leap Year Challenge Exercise', module: 'JavaScript', duration: 30, isProject: false },
  { id: 'lec-113', name: 'Leap Year Solution', module: 'JavaScript', duration: 183, isProject: false },
  { id: 'lec-114', name: 'Collections: Working with Javascript Arrays', module: 'JavaScript', duration: 541, isProject: false },
  { id: 'lec-115', name: 'Adding Elements and Intermediate Array Techniques', module: 'JavaScript', duration: 958, isProject: false },
  { id: 'lec-116', name: "Who's Buying Lunch? Code Challenge", module: 'JavaScript', duration: 30, isProject: false },
  { id: 'lec-117', name: "Who's Buying Lunch Solution", module: 'JavaScript', duration: 223, isProject: false },
  { id: 'lec-118', name: 'Control Statements: While Loops', module: 'JavaScript', duration: 472, isProject: false },
  { id: 'lec-119', name: 'Solution to the 99 Bottles Challenge', module: 'JavaScript', duration: 45, isProject: false },
  { id: 'lec-120', name: 'Control Statements: For Loops', module: 'JavaScript', duration: 370, isProject: false },
  { id: 'lec-121', name: 'Introducing the Fibonacci Code Challenge', module: 'JavaScript', duration: 397, isProject: false },
  { id: 'lec-122', name: 'The Fibonacci Exercise', module: 'JavaScript', duration: 30, isProject: false },
  { id: 'lec-123', name: 'Fibonacci Solution', module: 'JavaScript', duration: 496, isProject: false },
  { id: 'lec-124', name: 'Tip from Angela - Retrieval is How You Learn', module: 'JavaScript', duration: 172, isProject: false },

  // ─── DOM ─────────────────────────────────────────────────────────────
  { id: 'lec-125', name: 'Adding Javascript to Websites', module: 'DOM', duration: 644, isProject: false },
  { id: 'lec-126', name: 'Introduction to the Document Object Model (DOM)', module: 'DOM', duration: 748, isProject: false },
  { id: 'lec-127', name: 'Solution to the DOM Challenge', module: 'DOM', duration: 4, isProject: false },
  { id: 'lec-128', name: 'Selecting HTML Elements with Javascript', module: 'DOM', duration: 857, isProject: false },
  { id: 'lec-129', name: 'Manipulating and Changing Styles of HTML Elements with Javascript', module: 'DOM', duration: 301, isProject: false },
  { id: 'lec-130', name: 'The Separation of Concerns: Structure vs Style vs Behaviour', module: 'DOM', duration: 357, isProject: false },
  { id: 'lec-131', name: 'Text Manipulation and the Text Content Property', module: 'DOM', duration: 157, isProject: false },
  { id: 'lec-132', name: 'Manipulating HTML Element Attributes', module: 'DOM', duration: 147, isProject: false },
  { id: 'lec-133', name: 'Tip from Angela - The 20 Minute Method', module: 'DOM', duration: 159, isProject: false },
  { id: 'lec-134', name: 'Challenge: The Dicee Challenge', module: 'DOM', duration: 134, isProject: false },
  { id: 'lec-135', name: 'Dicee Challenge Step 0 - Download the Skeleton Project', module: 'DOM', duration: 7, isProject: false },
  { id: 'lec-136', name: 'Dicee Challenge Step 1 - Create an External Javascript File', module: 'DOM', duration: 3, isProject: false },
  { id: 'lec-137', name: 'Dicee Challenge Step 2 - Add Dice Images', module: 'DOM', duration: 6, isProject: false },
  { id: 'lec-138', name: 'Dicee Challenge Step 3 - Create a Random Number', module: 'DOM', duration: 9, isProject: false },
  { id: 'lec-139', name: 'Dicee Challenge Step 4 - Change the <img> to a Random Dice', module: 'DOM', duration: 14, isProject: false },
  { id: 'lec-140', name: 'Dicee Challenge Step 5 - Change both <img> Elements', module: 'DOM', duration: 2, isProject: false },
  { id: 'lec-141', name: 'Dicee Challenge Step 6 - Change the Title to Display a Winner', module: 'DOM', duration: 15, isProject: false },
  { id: 'lec-142', name: 'The Solution to the Dicee Challenge', module: 'DOM', duration: 883, isProject: false },
  { id: 'lec-143', name: 'Download the Completed Website', module: 'DOM', duration: 7, isProject: false },
  { id: 'lec-144', name: 'Tip from Angela - Learning Before you Eat', module: 'DOM', duration: 126, isProject: false },
  { id: 'lec-145', name: 'What We\'ll Make: Drum Kit', module: 'DOM', duration: 79, isProject: false },
  { id: 'lec-146', name: 'Download the Starting Files', module: 'DOM', duration: 7, isProject: false },
  { id: 'lec-147', name: 'Adding Event Listeners to a Button', module: 'DOM', duration: 869, isProject: false },
  { id: 'lec-148', name: 'Higher Order Functions and Passing Functions as Arguments', module: 'DOM', duration: 760, isProject: false },
  { id: 'lec-149', name: 'Higher Order Function Challenge Solution', module: 'DOM', duration: 8, isProject: false },
  { id: 'lec-150', name: 'How to Play Sounds on a Website', module: 'DOM', duration: 671, isProject: false },
  { id: 'lec-151', name: 'How to Use Switch Statements in Javascript', module: 'DOM', duration: 322, isProject: false },
  { id: 'lec-152', name: 'A Deeper Understanding of Javascript Objects', module: 'DOM', duration: 724, isProject: false },
  { id: 'lec-153', name: 'Objects, their Methods and the Dot Notation', module: 'DOM', duration: 389, isProject: false },
  { id: 'lec-154', name: 'A Quick Note About the Next Lesson', module: 'DOM', duration: 14, isProject: false },
  { id: 'lec-155', name: 'Using Keyboard Event Listeners to Check for Key Presses', module: 'DOM', duration: 457, isProject: false },
  { id: 'lec-156', name: 'Understanding Callbacks and How to Respond to Events', module: 'DOM', duration: 695, isProject: false },
  { id: 'lec-157', name: 'Adding Animation to Websites', module: 'DOM', duration: 511, isProject: false },
  { id: 'lec-158', name: 'Download the Completed Website', module: 'DOM', duration: 9, isProject: false },
  { id: 'lec-159', name: 'Tip from Angela - Dealing with Lack of Progress', module: 'DOM', duration: 188, isProject: false },

  // ─── jQuery ──────────────────────────────────────────────────────────
  { id: 'lec-160', name: 'What is jQuery?', module: 'jQuery', duration: 224, isProject: false },
  { id: 'lec-161', name: 'How to Incorporate jQuery into Websites', module: 'jQuery', duration: 548, isProject: false },
  { id: 'lec-162', name: 'How Minification Works to Reduce File Size', module: 'jQuery', duration: 238, isProject: false },
  { id: 'lec-163', name: 'Selecting Elements with jQuery', module: 'jQuery', duration: 121, isProject: false },
  { id: 'lec-164', name: 'Manipulating Styles with jQuery', module: 'jQuery', duration: 313, isProject: false },
  { id: 'lec-165', name: 'Manipulating Text with jQuery', module: 'jQuery', duration: 216, isProject: false },
  { id: 'lec-166', name: 'Manipulating Attributes with jQuery', module: 'jQuery', duration: 224, isProject: false },
  { id: 'lec-167', name: 'Adding Event Listeners with jQuery', module: 'jQuery', duration: 467, isProject: false },
  { id: 'lec-168', name: 'Adding and Removing Elements with jQuery', module: 'jQuery', duration: 178, isProject: false },
  { id: 'lec-169', name: 'Website Animations with jQuery', module: 'jQuery', duration: 493, isProject: false },
  { id: 'lec-170', name: 'Tip from Angela - Mixing Knowledge', module: 'jQuery', duration: 140, isProject: false },

  // ─── Simon Game ──────────────────────────────────────────────────────
  { id: 'lec-171', name: 'What You\'ll Make: The Simon Game', module: 'Simon Game', duration: 60, isProject: false },
  { id: 'lec-172', name: 'Play the Game', module: 'Simon Game', duration: 6, isProject: false },
  { id: 'lec-173', name: 'Step 0 - Download the Starting Files', module: 'Simon Game', duration: 30, isProject: false },
  { id: 'lec-174', name: 'Step 1 - Add Javascript and jQuery', module: 'Simon Game', duration: 25, isProject: false },
  { id: 'lec-175', name: 'Step 1 - Answer', module: 'Simon Game', duration: 29, isProject: false },
  { id: 'lec-176', name: 'Step 2 - Create A New Pattern', module: 'Simon Game', duration: 49, isProject: false },
  { id: 'lec-177', name: 'Step 2 - Answer', module: 'Simon Game', duration: 29, isProject: false },
  { id: 'lec-178', name: 'Step 3 - Show the Sequence to the User with Animations and Sounds', module: 'Simon Game', duration: 23, isProject: false },
  { id: 'lec-179', name: 'Step 3 - Answer', module: 'Simon Game', duration: 29, isProject: false },
  { id: 'lec-180', name: 'Step 4 - Check Which Button is Pressed', module: 'Simon Game', duration: 47, isProject: false },
  { id: 'lec-181', name: 'Step 4 - Answer', module: 'Simon Game', duration: 29, isProject: false },
  { id: 'lec-182', name: 'Step 5 - Add Sounds to Button Clicks', module: 'Simon Game', duration: 22, isProject: false },
  { id: 'lec-183', name: 'Step 5 - Answer', module: 'Simon Game', duration: 29, isProject: false },
  { id: 'lec-184', name: 'Step 6 - Add Animations to User Clicks', module: 'Simon Game', duration: 26, isProject: false },
  { id: 'lec-185', name: 'Step 6 - Answer', module: 'Simon Game', duration: 29, isProject: false },
  { id: 'lec-186', name: 'Step 7 - Start the Game', module: 'Simon Game', duration: 46, isProject: false },
  { id: 'lec-187', name: 'Step 7 - Answer', module: 'Simon Game', duration: 29, isProject: false },
  { id: 'lec-188', name: 'Step 8 - Check the User\'s Answer Against the Game Sequence', module: 'Simon Game', duration: 75, isProject: false },
  { id: 'lec-189', name: 'Step 8 - Answer', module: 'Simon Game', duration: 29, isProject: false },
  { id: 'lec-190', name: 'Step 9 - Game Over', module: 'Simon Game', duration: 22, isProject: false },
  { id: 'lec-191', name: 'Step 9 - Answer', module: 'Simon Game', duration: 29, isProject: false },
  { id: 'lec-192', name: 'Step 10 - Restart the Game', module: 'Simon Game', duration: 7, isProject: false },
  { id: 'lec-193', name: 'Step 10 - Answer', module: 'Simon Game', duration: 29, isProject: false },
  { id: 'lec-194', name: 'Download the Completed Project Code', module: 'Simon Game', duration: 20, isProject: false },
  { id: 'lec-195', name: 'Tip from Angela - Dealing with Frustration', module: 'Simon Game', duration: 151, isProject: false },

  // ─── Command Line ────────────────────────────────────────────────────
  { id: 'lec-196', name: 'Install Git Bash on Windows', module: 'Command Line', duration: 166, isProject: false },
  { id: 'lec-197', name: 'Understanding the Command Line. Long Live the Command Line!', module: 'Command Line', duration: 325, isProject: false },
  { id: 'lec-198', name: 'Command Line Techniques and Directory Navigation', module: 'Command Line', duration: 584, isProject: false },
  { id: 'lec-199', name: 'Creating, Opening, and Removing Files through the Command Line', module: 'Command Line', duration: 518, isProject: false },
  { id: 'lec-200', name: 'Tip from Angela - Sleep is My Secret Weapon', module: 'Command Line', duration: 228, isProject: false },

  // ─── Node.js ─────────────────────────────────────────────────────────
  { id: 'lec-201', name: 'Backend Web Development Explained', module: 'Node.js', duration: 913, isProject: false },
  { id: 'lec-202', name: 'Backend Tools and Technologies - Which one to learn?', module: 'Node.js', duration: 340, isProject: false },
  { id: 'lec-203', name: 'What is Node.js?', module: 'Node.js', duration: 639, isProject: false },
  { id: 'lec-204', name: 'Install Node.js on Mac', module: 'Node.js', duration: 35, isProject: false },
  { id: 'lec-205', name: 'Install Node.js on Windows', module: 'Node.js', duration: 26, isProject: false },
  { id: 'lec-206', name: 'Using Node.js', module: 'Node.js', duration: 503, isProject: false },
  { id: 'lec-207', name: 'How to Use the Native Node Modules', module: 'Node.js', duration: 732, isProject: false },
  { id: 'lec-208', name: 'A note about the next lesson', module: 'Node.js', duration: 14, isProject: false },
  { id: 'lec-209', name: 'The NPM Package Manager and Installing External Node Modules', module: 'Node.js', duration: 981, isProject: false },
  { id: 'lec-210', name: '[Project] QR Code Generator', module: 'Node.js', duration: 949, isProject: true },
  { id: 'lec-211', name: 'Tip from Angela - Step Up to the Challenge', module: 'Node.js', duration: 74, isProject: false },

  // ─── Express ─────────────────────────────────────────────────────────
  { id: 'lec-212', name: 'What is Express?', module: 'Express', duration: 419, isProject: false },
  { id: 'lec-213', name: 'Creating Our First Server with Express', module: 'Express', duration: 1295, isProject: false },
  { id: 'lec-214', name: 'HTTP Requests', module: 'Express', duration: 1424, isProject: false },
  { id: 'lec-215', name: 'Postman', module: 'Express', duration: 1155, isProject: false },
  { id: 'lec-216', name: 'Introduction to Middlewares', module: 'Express', duration: 1105, isProject: false },
  { id: 'lec-217', name: 'Custom Middlewares', module: 'Express', duration: 1168, isProject: false },
  { id: 'lec-218', name: 'Secrets Access Project', module: 'Express', duration: 501, isProject: true },
  { id: 'lec-219', name: 'Tip from Angela - How to Solidify Your Knowledge', module: 'Express', duration: 175, isProject: false },

  // ─── EJS ─────────────────────────────────────────────────────────────
  { id: 'lec-220', name: 'What is EJS?', module: 'EJS', duration: 1374, isProject: false },
  { id: 'lec-221', name: 'EJS Tags', module: 'EJS', duration: 1063, isProject: false },
  { id: 'lec-222', name: 'Passing Data to EJS Templates', module: 'EJS', duration: 1005, isProject: false },
  { id: 'lec-223', name: 'EJS Partials and Layouts', module: 'EJS', duration: 1088, isProject: false },
  { id: 'lec-224', name: 'Band Generator Project', module: 'EJS', duration: 721, isProject: true },
  { id: 'lec-225', name: 'Tip from Angela - Location, Location, Location!', module: 'EJS', duration: 126, isProject: false },

  // ─── Git ─────────────────────────────────────────────────────────────
  { id: 'lec-226', name: 'Instructions', module: 'Git', duration: 196, isProject: false },
  { id: 'lec-227', name: 'Introduction to Version Control and Git', module: 'Git', duration: 124, isProject: false },
  { id: 'lec-228', name: 'Version Control Using Git and the Command Line', module: 'Git', duration: 858, isProject: false },
  { id: 'lec-229', name: 'GitHub and Remote Repositories', module: 'Git', duration: 622, isProject: false },
  { id: 'lec-230', name: 'Gitignore', module: 'Git', duration: 659, isProject: false },
  { id: 'lec-231', name: 'Cloning', module: 'Git', duration: 568, isProject: false },
  { id: 'lec-232', name: 'Branching and Merging', module: 'Git', duration: 629, isProject: false },
  { id: 'lec-233', name: 'Optional Git Challenge', module: 'Git', duration: 5, isProject: false },
  { id: 'lec-234', name: 'Forking and Pull Requests', module: 'Git', duration: 917, isProject: false },
  { id: 'lec-235', name: 'Tip from Angela - Spaced Repetition', module: 'Git', duration: 241, isProject: false },

  // ─── APIs ────────────────────────────────────────────────────────────
  { id: 'lec-236', name: 'Introduction to APIs', module: 'APIs', duration: 1167, isProject: false },
  { id: 'lec-237', name: 'Structuring API Requests', module: 'APIs', duration: 862, isProject: false },
  { id: 'lec-238', name: 'What is JSON?', module: 'APIs', duration: 1076, isProject: false },
  { id: 'lec-239', name: 'Making Server-Side API Requests with Axios', module: 'APIs', duration: 1080, isProject: false },
  { id: 'lec-240', name: 'API Authentication', module: 'APIs', duration: 2265, isProject: false },
  { id: 'lec-241', name: 'REST APIs', module: 'APIs', duration: 1517, isProject: false },
  { id: 'lec-242', name: 'Secrets Project', module: 'APIs', duration: 721, isProject: true },
  { id: 'lec-243', name: 'Tip from Angela - Use Accountability in your Favour', module: 'APIs', duration: 176, isProject: false },
  { id: 'lec-244', name: 'Instructions', module: 'APIs', duration: 136, isProject: false },
  { id: 'lec-245', name: 'Building your own APIs', module: 'APIs', duration: 1069, isProject: false },
  { id: 'lec-246', name: 'Creating GET Routes', module: 'APIs', duration: 1257, isProject: false },
  { id: 'lec-247', name: 'Creating POST, PUT, and PATCH Routes', module: 'APIs', duration: 876, isProject: false },
  { id: 'lec-248', name: 'Creating the DELETE Route', module: 'APIs', duration: 392, isProject: false },
  { id: 'lec-249', name: 'Build your own API for a Blog', module: 'APIs', duration: 894, isProject: true },
  { id: 'lec-250', name: 'Tip from Angela - How to Get a Job as Programmer', module: 'APIs', duration: 126, isProject: false },

  // ─── SQL ─────────────────────────────────────────────────────────────
  { id: 'lec-251', name: 'Databases Explained: SQL vs. NoSQL', module: 'SQL', duration: 944, isProject: false },
  { id: 'lec-252', name: 'Tip from Angela - When Life Gives You Lemons', module: 'SQL', duration: 361, isProject: false },
  { id: 'lec-253', name: 'SQL Commands: CREATE Table and INSERT Data', module: 'SQL', duration: 828, isProject: false },
  { id: 'lec-254', name: 'SQL Commands: READ, SELECT, and WHERE', module: 'SQL', duration: 190, isProject: false },
  { id: 'lec-255', name: 'Updating Single Values and Adding Columns in SQL', module: 'SQL', duration: 282, isProject: false },
  { id: 'lec-256', name: 'SQL Commands: DELETE', module: 'SQL', duration: 92, isProject: false },
  { id: 'lec-257', name: 'Understanding SQL Relationships, Foreign Keys and Inner Joins', module: 'SQL', duration: 673, isProject: false },
  { id: 'lec-258', name: 'Tip from Angela - Find All the Hard Working People', module: 'SQL', duration: 121, isProject: false },

  // ─── PostgreSQL ──────────────────────────────────────────────────────
  { id: 'lec-259', name: 'Introduction to Postgres', module: 'PostgreSQL', duration: 490, isProject: false },
  { id: 'lec-260', name: 'How to Install PostgreSQL and pgAdmin', module: 'PostgreSQL', duration: 52, isProject: false },
  { id: 'lec-261', name: 'Understand how to use keys, Postgres types and keywords', module: 'PostgreSQL', duration: 631, isProject: false },
  { id: 'lec-262', name: 'Flag Emojis on Windows', module: 'PostgreSQL', duration: 33, isProject: false },
  { id: 'lec-263', name: 'Use pgAdmin to CREATE a TABLE', module: 'PostgreSQL', duration: 1025, isProject: false },
  { id: 'lec-264', name: 'READ data from a Postgres database', module: 'PostgreSQL', duration: 1388, isProject: false },
  { id: 'lec-265', name: 'Query data using SELECT, WHERE, and LIKE', module: 'PostgreSQL', duration: 1158, isProject: false },
  { id: 'lec-266', name: 'UNIQUE and NOT NULL | Travel Tracker Part 1', module: 'PostgreSQL', duration: 1130, isProject: false },
  { id: 'lec-267', name: 'INSERT and add Data | Travel Tracker Part 2', module: 'PostgreSQL', duration: 1032, isProject: false },
  { id: 'lec-268', name: 'Travel Tracker Part 3', module: 'PostgreSQL', duration: 685, isProject: false },
  { id: 'lec-269', name: 'One to One Relationships & Inner Joins', module: 'PostgreSQL', duration: 719, isProject: false },
  { id: 'lec-270', name: 'One to Many Relationships', module: 'PostgreSQL', duration: 803, isProject: false },
  { id: 'lec-271', name: 'Many to Many Relationships & Aliases', module: 'PostgreSQL', duration: 748, isProject: false },
  { id: 'lec-272', name: 'The Family Travel Tracker', module: 'PostgreSQL', duration: 2089, isProject: true },
  { id: 'lec-273', name: 'How to update and delete data & tables', module: 'PostgreSQL', duration: 1137, isProject: false },
  { id: 'lec-274', name: 'Permalist Project', module: 'PostgreSQL', duration: 1799, isProject: true },
  { id: 'lec-275', name: 'Tip from Angela - Daily Routines', module: 'PostgreSQL', duration: 154, isProject: false },
  { id: 'lec-276', name: 'Instructions', module: 'PostgreSQL', duration: 132, isProject: false },

  // ─── Authentication ──────────────────────────────────────────────────
  { id: 'lec-277', name: 'Introduction to Authentication', module: 'Authentication', duration: 341, isProject: false },
  { id: 'lec-278', name: 'Level 1 - Registering Users with Email and Password', module: 'Authentication', duration: 1320, isProject: false },
  { id: 'lec-279', name: 'Level 2 - Encryption and Hashing', module: 'Authentication', duration: 961, isProject: false },
  { id: 'lec-280', name: 'How to Hack Passwords', module: 'Authentication', duration: 746, isProject: false },
  { id: 'lec-281', name: 'Level 3 - How to Salt Passwords for Improved Encryption', module: 'Authentication', duration: 1131, isProject: false },
  { id: 'lec-282', name: 'Managing Cookies and Sessions', module: 'Authentication', duration: 2007, isProject: false },
  { id: 'lec-283', name: 'Level 5 - Hide your Secrets with Environment Variables', module: 'Authentication', duration: 1037, isProject: false },
  { id: 'lec-284', name: 'Set up your Google OAuth Credentials', module: 'Authentication', duration: 103, isProject: false },
  { id: 'lec-285', name: 'Level 6 - OAuth: Implement Sign In with Google', module: 'Authentication', duration: 1856, isProject: false },
  { id: 'lec-286', name: 'Finish the app: let users submit secrets', module: 'Authentication', duration: 940, isProject: false },
  { id: 'lec-287', name: 'Tip from Angela - How to Work as a Freelancer', module: 'Authentication', duration: 97, isProject: false },

  // ─── React ───────────────────────────────────────────────────────────
  { id: 'lec-288', name: 'What is React?', module: 'React', duration: 448, isProject: false },
  { id: 'lec-289', name: 'What we will make in this React module', module: 'React', duration: 94, isProject: false },
  { id: 'lec-290', name: 'Introduction to Code Sandbox and the Structure of the Module', module: 'React', duration: 345, isProject: false },
  { id: 'lec-291', name: '[Optional] Local Development Setup', module: 'React', duration: 104, isProject: false },
  { id: 'lec-292', name: 'Introduction to JSX and Babel', module: 'React', duration: 1019, isProject: false },
  { id: 'lec-293', name: 'JSX Code Practice', module: 'React', duration: 450, isProject: false },
  { id: 'lec-294', name: 'Javascript Expressions in JSX & ES6 Template Literals', module: 'React', duration: 702, isProject: false },
  { id: 'lec-295', name: 'Javascript Expressions in JSX Practice', module: 'React', duration: 514, isProject: false },
  { id: 'lec-296', name: 'JSX Attributes & Styling React Elements', module: 'React', duration: 1018, isProject: false },
  { id: 'lec-297', name: 'Inline Styling for React Elements', module: 'React', duration: 521, isProject: false },
  { id: 'lec-298', name: 'React Styling Practice', module: 'React', duration: 599, isProject: false },
  { id: 'lec-299', name: 'React Components', module: 'React', duration: 947, isProject: false },
  { id: 'lec-300', name: 'React Components Practice', module: 'React', duration: 301, isProject: false },
  { id: 'lec-301', name: 'Javascript ES6 - Import, Export and Modules', module: 'React', duration: 670, isProject: false },
  { id: 'lec-302', name: 'Javascript ES6 Import, Export and Modules Practice', module: 'React', duration: 244, isProject: false },
  { id: 'lec-303', name: 'Keeper App Project - Part 1 Challenge', module: 'React', duration: 297, isProject: true },
  { id: 'lec-304', name: 'Keeper App Part 1 Solution', module: 'React', duration: 847, isProject: false },
  { id: 'lec-305', name: 'React Props', module: 'React', duration: 1004, isProject: false },
  { id: 'lec-306', name: 'React Props Practice', module: 'React', duration: 799, isProject: false },
  { id: 'lec-307', name: 'React DevTools', module: 'React', duration: 1039, isProject: false },
  { id: 'lec-308', name: 'Mapping Data to Components', module: 'React', duration: 620, isProject: false },
  { id: 'lec-309', name: 'Mapping Data to Components Practice', module: 'React', duration: 1050, isProject: false },
  { id: 'lec-310', name: 'Javascript ES6 Map/Filter/Reduce', module: 'React', duration: 1221, isProject: false },
  { id: 'lec-311', name: 'Javascript ES6 Arrow functions', module: 'React', duration: 596, isProject: false },
  { id: 'lec-312', name: 'Keeper App Project - Part 2', module: 'React', duration: 623, isProject: true },
  { id: 'lec-313', name: 'React Conditional Rendering with the Ternary Operator & AND Operator', module: 'React', duration: 1164, isProject: false },
  { id: 'lec-314', name: 'Conditional Rendering Practice', module: 'React', duration: 393, isProject: false },
  { id: 'lec-315', name: 'State in React - Declarative vs. Imperative Programming', module: 'React', duration: 578, isProject: false },
  { id: 'lec-316', name: 'React Hooks - useState', module: 'React', duration: 1089, isProject: false },
  { id: 'lec-317', name: 'useState Hook Practice', module: 'React', duration: 444, isProject: false },
  { id: 'lec-318', name: 'Javascript ES6 Object & Array Destructuring', module: 'React', duration: 1064, isProject: false },
  { id: 'lec-319', name: 'Javascript ES6 Destructuring Challenge Solution', module: 'React', duration: 348, isProject: false },
  { id: 'lec-320', name: 'Event Handling in React', module: 'React', duration: 670, isProject: false },
  { id: 'lec-321', name: 'React Forms', module: 'React', duration: 820, isProject: false },
  { id: 'lec-322', name: 'Class Components vs. Functional Components', module: 'React', duration: 384, isProject: false },
  { id: 'lec-323', name: 'Changing Complex State', module: 'React', duration: 1183, isProject: false },
  { id: 'lec-324', name: 'Changing Complex State Practice', module: 'React', duration: 428, isProject: false },
  { id: 'lec-325', name: 'Javascript ES6 Spread Operator', module: 'React', duration: 658, isProject: false },
  { id: 'lec-326', name: 'Javascript ES6 Spread Operator Practice', module: 'React', duration: 740, isProject: false },
  { id: 'lec-327', name: 'Managing a Component Tree', module: 'React', duration: 1357, isProject: false },
  { id: 'lec-328', name: 'Managing a Component Tree Practice', module: 'React', duration: 507, isProject: false },
  { id: 'lec-329', name: 'Keeper App Project - Part 3', module: 'React', duration: 1505, isProject: true },
  { id: 'lec-330', name: 'Note about the Next Lesson - Packages and Imports', module: 'React', duration: 50, isProject: false },
  { id: 'lec-331', name: 'React Dependencies & Styling the Keeper App', module: 'React', duration: 998, isProject: false },
  { id: 'lec-332', name: 'Tip from Angela - How to Build Your Own Product', module: 'React', duration: 134, isProject: false },

  // ─── Web3 ────────────────────────────────────────────────────────────
  { id: 'lec-333', name: 'What is Web3?', module: 'Web3', duration: 458, isProject: false },
  { id: 'lec-334', name: 'How does the Blockchain actually work?', module: 'Web3', duration: 1545, isProject: false },
  { id: 'lec-335', name: 'What are DApps (Decentralised Apps) and how do you develop them?', module: 'Web3', duration: 558, isProject: false },
  { id: 'lec-336', name: 'What is the Internet Computer (ICP)?', module: 'Web3', duration: 558, isProject: false },
  { id: 'lec-337', name: 'Read Me!', module: 'Web3', duration: 40, isProject: false },
  { id: 'lec-338', name: '[Mac Users] Installation and Setup for Web3 Development', module: 'Web3', duration: 423, isProject: false },
  { id: 'lec-339', name: '[Windows Users] Installation and Setup for Web3 Development', module: 'Web3', duration: 765, isProject: false },
  { id: 'lec-340', name: "What You'll Build - DBANK (Inspired by Compound)", module: 'Web3', duration: 136, isProject: false },
  { id: 'lec-341', name: 'Introduction to the Motoko Language', module: 'Web3', duration: 756, isProject: false },
  { id: 'lec-342', name: 'Motoko Functions and the Candid User Interface', module: 'Web3', duration: 960, isProject: false },
  { id: 'lec-343', name: 'Motoko Conditionals and Type Annotations', module: 'Web3', duration: 334, isProject: false },
  { id: 'lec-344', name: 'Query vs. Update Methods', module: 'Web3', duration: 489, isProject: false },
  { id: 'lec-345', name: 'Orthogonal Persistance', module: 'Web3', duration: 483, isProject: false },
  { id: 'lec-346', name: 'Tracking Time and Calculating Compound Interest', module: 'Web3', duration: 1055, isProject: false },
  { id: 'lec-347', name: 'Motoko Language Quiz', module: 'Web3', duration: 30, isProject: false },
  { id: 'lec-348', name: 'Adding HTML and CSS to Create the Frontend for DBANK', module: 'Web3', duration: 455, isProject: false },
  { id: 'lec-349', name: 'Connecting the Motoko Backend to our JS Frontend', module: 'Web3', duration: 1627, isProject: false },
  { id: 'lec-350', name: 'Where to Get Help and Support for Development on the Internet Computer', module: 'Web3', duration: 21, isProject: false },
  { id: 'lec-351', name: 'What are Cycles and the ICP Token?', module: 'Web3', duration: 427, isProject: false },
  { id: 'lec-352', name: 'How to Claim Free Cycles from Dfinity', module: 'Web3', duration: 163, isProject: false },
  { id: 'lec-353', name: 'How to Deploy to the ICP Network', module: 'Web3', duration: 183, isProject: false },
  { id: 'lec-354', name: 'How to Convert ICP into Cycles?', module: 'Web3', duration: 357, isProject: false },
  { id: 'lec-355', name: '[Optional] How to Deploy a Static Website onto the ICP Blockchain for Hosting', module: 'Web3', duration: 457, isProject: false },
  { id: 'lec-356', name: 'How to Configure a DFX Created Project to Use React', module: 'Web3', duration: 685, isProject: false },
  { id: 'lec-357', name: 'Storing Data on a Canister', module: 'Web3', duration: 964, isProject: false },
  { id: 'lec-358', name: 'Retrieving Data from a Canister', module: 'Web3', duration: 718, isProject: false },
  { id: 'lec-359', name: 'Deleting and Persistance', module: 'Web3', duration: 995, isProject: false },
  { id: 'lec-360', name: 'Tokens and Coins: What are they and how are they used?', module: 'Web3', duration: 557, isProject: false },
  { id: 'lec-361', name: 'Download and Configure the Skeleton Project', module: 'Web3', duration: 370, isProject: false },
  { id: 'lec-362', name: 'Using Motoko Hashmaps to Store Token Balances', module: 'Web3', duration: 1174, isProject: false },
  { id: 'lec-363', name: 'Showing the User\'s Token Balance on the Frontend', module: 'Web3', duration: 838, isProject: false },
  { id: 'lec-364', name: 'Creating the Faucet Functionality Using the Shared Keyword', module: 'Web3', duration: 916, isProject: false },
  { id: 'lec-365', name: 'Creating the Transfer Functionality', module: 'Web3', duration: 1252, isProject: false },
  { id: 'lec-366', name: 'Using the Transfer Functionality in the Faucet', module: 'Web3', duration: 399, isProject: false },
  { id: 'lec-367', name: 'Persisting Non-Stable Types Using the Pre- and Postupgrade Methods', module: 'Web3', duration: 943, isProject: false },
  { id: 'lec-368', name: 'What is the Internet Identity?', module: 'Web3', duration: 330, isProject: false },
  { id: 'lec-369', name: 'Authenticating with the Internet Identity', module: 'Web3', duration: 476, isProject: false },
  { id: 'lec-370', name: '[Optional] Live Deployment to Test Internet Identity Authentication', module: 'Web3', duration: 1107, isProject: false },
  { id: 'lec-371', name: "What You'll Build - A Website to Mint, Buy and Sell NFTs", module: 'Web3', duration: 623, isProject: false },
  { id: 'lec-372', name: 'Minting NFTs', module: 'Web3', duration: 1003, isProject: false },
  { id: 'lec-373', name: 'Viewing the NFT on the Frontend', module: 'Web3', duration: 1202, isProject: false },
  { id: 'lec-374', name: 'Enabling the Minting Functionality on the Frontend', module: 'Web3', duration: 1838, isProject: false },
  { id: 'lec-375', name: 'Displaying Owned NFTs Using the React Router', module: 'Web3', duration: 2199, isProject: false },
  { id: 'lec-376', name: 'Listing NFTs for Sale', module: 'Web3', duration: 2028, isProject: false },
  { id: 'lec-377', name: 'Styling the Listed NFTs', module: 'Web3', duration: 676, isProject: false },
  { id: 'lec-378', name: 'Creating the Discover Page', module: 'Web3', duration: 1357, isProject: false },
  { id: 'lec-379', name: 'Buying NFTs', module: 'Web3', duration: 1922, isProject: false },
  { id: 'lec-380', name: 'Join the $6 Million Dollar Supernova Hackathon', module: 'Web3', duration: 17, isProject: false },

  // ─── AMA ─────────────────────────────────────────────────────────────
  { id: 'lec-381', name: 'AAA 1 - How to Soak in Programming Concepts and more...', module: 'AMA', duration: 2382, isProject: false },
  { id: 'lec-382', name: 'AAA 2 - Schedule for Learning to Code and more...', module: 'AMA', duration: 2348, isProject: false },
  { id: 'lec-383', name: 'AAA 3 - How to Start Freelancing and more...', module: 'AMA', duration: 1519, isProject: false },
  { id: 'lec-384', name: 'AAA 4 - The Live AMA', module: 'AMA', duration: 3592, isProject: false },
  { id: 'lec-385', name: 'Vote for the Next Module!', module: 'AMA', duration: 12, isProject: false },

  // ─── Bonus ───────────────────────────────────────────────────────────
  { id: 'lec-386', name: 'Bonus', module: 'Bonus', duration: 30, isProject: false },
];

export const SEED_PROJECTS: Omit<Project, 'status' | 'completionDate' | 'notes' | 'githubLink' | 'demoLink'>[] = [
  { id: 'proj-001', name: 'Movie Ranking', module: 'HTML', difficulty: 'beginner' },
  { id: 'proj-002', name: 'Birthday Invite', module: 'HTML', difficulty: 'beginner' },
  { id: 'proj-003', name: 'Portfolio Website', module: 'HTML', difficulty: 'beginner' },
  { id: 'proj-004', name: 'Online Resume', module: 'HTML', difficulty: 'beginner' },
  { id: 'proj-005', name: 'Colour Vocab Website', module: 'CSS', difficulty: 'beginner' },
  { id: 'proj-006', name: 'Motivational Poster Website', module: 'CSS', difficulty: 'beginner' },
  { id: 'proj-007', name: 'CSS Flag', module: 'CSS', difficulty: 'intermediate' },
  { id: 'proj-008', name: 'Web Design Agency Website', module: 'CSS', difficulty: 'intermediate' },
  { id: 'proj-009', name: 'Pricing Table', module: 'Flexbox', difficulty: 'intermediate' },
  { id: 'proj-010', name: 'Mondrian Painting', module: 'Grid', difficulty: 'intermediate' },
  { id: 'proj-011', name: 'TinDog Startup Website', module: 'Bootstrap', difficulty: 'intermediate' },
  { id: 'proj-012', name: 'Dicee', module: 'DOM', difficulty: 'beginner' },
  { id: 'proj-013', name: 'Drum Kit', module: 'DOM', difficulty: 'intermediate' },
  { id: 'proj-014', name: 'Simon Game', module: 'Simon Game', difficulty: 'advanced' },
  { id: 'proj-015', name: 'QR Code Generator', module: 'Node.js', difficulty: 'beginner' },
  { id: 'proj-016', name: 'Secrets Access Project', module: 'Express', difficulty: 'intermediate' },
  { id: 'proj-017', name: 'Band Generator', module: 'EJS', difficulty: 'beginner' },
  { id: 'proj-018', name: 'Blog API', module: 'APIs', difficulty: 'intermediate' },
  { id: 'proj-019', name: 'Secrets Project', module: 'APIs', difficulty: 'intermediate' },
  { id: 'proj-020', name: 'Travel Tracker', module: 'PostgreSQL', difficulty: 'intermediate' },
  { id: 'proj-021', name: 'Family Travel Tracker', module: 'PostgreSQL', difficulty: 'advanced' },
  { id: 'proj-022', name: 'Permalist', module: 'PostgreSQL', difficulty: 'intermediate' },
  { id: 'proj-023', name: 'Keeper App', module: 'React', difficulty: 'intermediate' },
  { id: 'proj-024', name: 'DBANK', module: 'Web3', difficulty: 'advanced' },
  { id: 'proj-025', name: 'NFT Marketplace', module: 'Web3', difficulty: 'advanced' },
];
